AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: The AWS CloudFormation template for the Google Calendar Serverless application
Resources:
  GocalPersonal:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: gocalpersonal
      Runtime: go1.x
      Timeout: 10
      Policies:
      - AWSLambdaRole
      - AmazonSSMReadOnlyAccess
      Tracing: Active
      Events:
        GocalPersonalSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 */2 * * ? *)
      Environment:
        Variables:
          arntrello: xxx
          cspointer: xxx
          interval: xxx
          tokenpointer: xxx
      Tags:
        commit: xxx